name: dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

env:
  PR_URL: ${{github.event.pull_request.html_url}}
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: approve
        run: gh pr review --approve "$PR_URL"
      - name: merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
